
#pragma once

#ifdef __cplusplus
	#error "bootstrap not supported from C++"
#endif

// NOTE: generated by https://github.com/Totto16/c_variant_generator
// 4118de284c6346aca8167ed6ecf9a15fbdeda9a1 v1.1.4

// manually stripped an changed in some parts

#define __INTERNAL_VARIANT_DECLARATION_START_IMPL_()
#define __INTERNAL_VARIANT_DECLARATION_END_IMPL_()

// NOTE: generated by https://github.com/Totto16/c_variant_generator
// 4118de284c6346aca8167ed6ecf9a15fbdeda9a1 v1.1.4

// manually stripped an changed in some parts

#include <tstr.h>

// utils macros

#if !defined(VARIANT_IMPL_JSON_VARIANTS_COMPILED_WITH_NARROWED_ENUMS)
	#error \
	    "define 'VARIANT_IMPL_JSON_VARIANTS_COMPILED_WITH_NARROWED_ENUMS' to make enums work in all cases"
#elif VARIANT_IMPL_JSON_VARIANTS_COMPILED_WITH_NARROWED_ENUMS == 1
	#define _IMPL_JSON_VARIANTS_C_23_NARROW_ENUM_TO(x) : x
#elif VARIANT_IMPL_JSON_VARIANTS_COMPILED_WITH_NARROWED_ENUMS == 0
	#define _IMPL_JSON_VARIANTS_C_23_NARROW_ENUM_TO(x)
#else
	#error \
	    "value of 'VARIANT_IMPL_JSON_VARIANTS_COMPILED_WITH_NARROWED_ENUMS' can only be 0 or 1 (like a boolean)"
#endif

#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202000) || __cplusplus
	#define JSON_VARIANTS_NODISCARD [[nodiscard]]
	#define JSON_VARIANTS_MAYBE_UNUSED [[maybe_unused]]
#else
    // see e.g. https://www.gnu.org/software/gnulib/manual/html_node/Attributes.html
	#define JSON_VARIANTS_NODISCARD __attribute__((__warn_unused_result__))
	#define JSON_VARIANTS_MAYBE_UNUSED __attribute__((__unused__))
#endif

#define JSON_VARIANTS_UNUSED(v) ((void)(v))

// cool trick from here:
// https://stackoverflow.com/questions/777261/avoiding-unused-variables-warnings-when-using-assert-in-a-release-build
#ifdef NDEBUG
	#define JSON_VARIANTS_UNREACHABLE() \
		do { \
			fprintf(stderr, "[%s %s:%d]: UNREACHABLE\n", __func__, __FILE__, __LINE__); \
			exit(EXIT_FAILURE); \
		} while(false)
#else
	#include <assert.h>

	#define JSON_VARIANTS_UNREACHABLE() \
		do { \
			assert(false && "UNREACHABLE"); /* NOLINT(cert-dcl03-c,misc-static-assert) */ \
		} while(false)
#endif

// end utils macros

#ifndef VARIANT_CASE_END
	#define VARIANT_CASE_END() \
		JSON_VARIANTS_UNREACHABLE_WITH_MESSAGE_SINGLE( \
		    "macro trick with for loops for getting the value was implemented wrong")
#endif

#ifndef VARIANT_STATE_ASSERT
	#define VARIANT_STATE_ASSERT(state, expected_state, variant_name, VariantName) \
		do { \
			if((state) != (expected_state)) { \
				tstr_static const state_str = \
				    _impl_get_state_string_for_variant_##variant_name(state); \
				tstr_static const expected_state_str = \
				    _impl_get_state_string_for_variant_##variant_name(expected_state); \
				JSON_VARIANTS_UNREACHABLE_WITH_MESSAGE( \
				    "Invalid variant access for variant '%s': state was " TSTR_FMT \
				    " but expected " TSTR_FMT, \
				    VariantName, TSTR_STATIC_FMT_ARGS(state_str), \
				    TSTR_STATIC_FMT_ARGS(expected_state_str)); \
			} \
		} while(false)
#endif

#define JSON_VARIANTS_UNREACHABLE_WITH_MESSAGE(msg, ...) \
	do { \
		fprintf(stderr, "[%s %s:%d]: UNREACHABLE: " msg "\n", __func__, __FILE__, __LINE__, \
		        __VA_ARGS__); \
		JSON_VARIANTS_UNREACHABLE(); \
	} while(false)

#define JSON_VARIANTS_UNREACHABLE_WITH_MESSAGE_SINGLE(msg) \
	JSON_VARIANTS_UNREACHABLE_WITH_MESSAGE(msg "%s", "")

#define VARIANT_JSON_VALUE_STATE_ASSERT(state, expected_state) \
	VARIANT_STATE_ASSERT(state, expected_state, json_value, "JsonValue")

#define GENERATE_VARIANT_ENUM_JSON_VALUE() \
	/* @enum value */ \
	typedef enum _IMPL_JSON_VARIANTS_C_23_NARROW_ENUM_TO(uint8_t) { \
		JsonValueTypeObject = 0, \
		JsonValueTypeArray, \
		JsonValueTypeNumber, \
		JsonValueTypeString, \
		JsonValueTypeBoolean, \
		JsonValueTypeNull \
	} JsonValueType;

#define GENERATE_VARIANT_CORE_JSON_VALUE() \
	__INTERNAL_VARIANT_DECLARATION_START_IMPL_() \
	typedef struct { \
		JsonObject* obj; \
	} _variant_impl_unnamed_struct_for_variant_json_value_id_0_name_object_impl_; \
\
	typedef struct { \
		JsonArray* arr; \
	} _variant_impl_unnamed_struct_for_variant_json_value_id_1_name_array_impl_; \
\
	/* raw union for variant */ \
	typedef union { \
		_variant_impl_unnamed_struct_for_variant_json_value_id_0_name_object_impl_ object; \
		_variant_impl_unnamed_struct_for_variant_json_value_id_1_name_array_impl_ array; \
		JsonNumber number; \
		JsonString* string; \
		JsonBoolean boolean; \
	} _AnonymousUnionForVariantJsonValueImpl_DONT_USE; \
\
	/* tagged union (variant) implementation */ \
	typedef struct { \
		JsonValueType _variant_tag_for_json_value_tag_member; \
		_AnonymousUnionForVariantJsonValueImpl_DONT_USE _variant_data_for_json_value_data_member; \
	} JsonValue; \
	typedef struct { \
		JsonValueType _variant_tag_for_json_value_tag_member; \
		_AnonymousUnionForVariantJsonValueImpl_DONT_USE _variant_data_for_json_value_data_member; \
	} AssertTypeImplForJsonValueImpl_1_DONT_USE_; \
	typedef struct { \
		_AnonymousUnionForVariantJsonValueImpl_DONT_USE _variant_data_for_json_value_data_member; \
		JsonValueType _variant_tag_for_json_value_tag_member; \
	} AssertTypeImplForJsonValueImpl_2_DONT_USE_; \
	static_assert(sizeof(AssertTypeImplForJsonValueImpl_1_DONT_USE_) <= \
	                  sizeof(AssertTypeImplForJsonValueImpl_2_DONT_USE_), \
	              "Size for variant JsonValue not smaller as the inverted order, current order: " \
	              "tag is first"); \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline tstr_static \
	_impl_get_state_string_for_variant_json_value(JsonValueType const enum_value) { \
		_Pragma("GCC diagnostic push") \
		    _Pragma("GCC diagnostic ignored \"-Wswitch-bool\"") /* FOR GCC */ \
		    switch(enum_value) { \
		_Pragma("GCC diagnostic pop") case JsonValueTypeObject: { \
			return TSTR_STATIC_LIT("object"); \
		} \
		case JsonValueTypeArray: { \
			return TSTR_STATIC_LIT("array"); \
		} \
		case JsonValueTypeNumber: { \
			return TSTR_STATIC_LIT("number"); \
		} \
		case JsonValueTypeString: { \
			return TSTR_STATIC_LIT("string"); \
		} \
		case JsonValueTypeBoolean: { \
			return TSTR_STATIC_LIT("boolean"); \
		} \
		case JsonValueTypeNull: { \
			return TSTR_STATIC_LIT("null"); \
		} \
		default: { \
			return TSTR_STATIC_LIT("<unknown>"); \
		} \
		} \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonValueType \
	get_current_tag_type_for_json_value(JsonValue const variant_entry) { \
		return variant_entry._variant_tag_for_json_value_tag_member; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonValue \
	new_json_value_object(JsonObject* const obj) { \
		return (JsonValue){ \
			._variant_tag_for_json_value_tag_member = JsonValueTypeObject, \
			._variant_data_for_json_value_data_member = \
			    (_AnonymousUnionForVariantJsonValueImpl_DONT_USE){ \
			        .object = \
			            (_variant_impl_unnamed_struct_for_variant_json_value_id_0_name_object_impl_){ \
			                .obj = obj } } \
		}; \
	} \
\
	JSON_VARIANTS_NODISCARD \
	JSON_VARIANTS_MAYBE_UNUSED static inline _variant_impl_unnamed_struct_for_variant_json_value_id_0_name_object_impl_ \
	json_value_get_as_object(JsonValue const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry._variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeObject); \
		return variant_entry._variant_data_for_json_value_data_member.object; \
	} \
\
	JSON_VARIANTS_NODISCARD \
	JSON_VARIANTS_MAYBE_UNUSED static inline _variant_impl_unnamed_struct_for_variant_json_value_id_0_name_object_impl_* \
	json_value_get_as_object_mut_ref(JsonValue* const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry->_variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeObject); \
		return &(variant_entry->_variant_data_for_json_value_data_member.object); \
	} \
\
	JSON_VARIANTS_NODISCARD \
	JSON_VARIANTS_MAYBE_UNUSED static inline const _variant_impl_unnamed_struct_for_variant_json_value_id_0_name_object_impl_* \
	json_value_get_as_object_const_ref(const JsonValue* const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry->_variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeObject); \
		return &(variant_entry->_variant_data_for_json_value_data_member.object); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonValue \
	new_json_value_array(JsonArray* const arr) { \
		return (JsonValue){ \
			._variant_tag_for_json_value_tag_member = JsonValueTypeArray, \
			._variant_data_for_json_value_data_member = \
			    (_AnonymousUnionForVariantJsonValueImpl_DONT_USE){ \
			        .array = \
			            (_variant_impl_unnamed_struct_for_variant_json_value_id_1_name_array_impl_){ \
			                .arr = arr } } \
		}; \
	} \
\
	JSON_VARIANTS_NODISCARD \
	JSON_VARIANTS_MAYBE_UNUSED static inline _variant_impl_unnamed_struct_for_variant_json_value_id_1_name_array_impl_ \
	json_value_get_as_array(JsonValue const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry._variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeArray); \
		return variant_entry._variant_data_for_json_value_data_member.array; \
	} \
\
	JSON_VARIANTS_NODISCARD \
	JSON_VARIANTS_MAYBE_UNUSED static inline _variant_impl_unnamed_struct_for_variant_json_value_id_1_name_array_impl_* \
	json_value_get_as_array_mut_ref(JsonValue* const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry->_variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeArray); \
		return &(variant_entry->_variant_data_for_json_value_data_member.array); \
	} \
\
	JSON_VARIANTS_NODISCARD \
	JSON_VARIANTS_MAYBE_UNUSED static inline const _variant_impl_unnamed_struct_for_variant_json_value_id_1_name_array_impl_* \
	json_value_get_as_array_const_ref(const JsonValue* const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry->_variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeArray); \
		return &(variant_entry->_variant_data_for_json_value_data_member.array); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonValue \
	new_json_value_number(JsonNumber const value) { \
		return (JsonValue){ ._variant_tag_for_json_value_tag_member = JsonValueTypeNumber, \
			                ._variant_data_for_json_value_data_member = \
			                    (_AnonymousUnionForVariantJsonValueImpl_DONT_USE){ .number = \
			                                                                           value } }; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonNumber \
	json_value_get_as_number(JsonValue const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry._variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeNumber); \
		return variant_entry._variant_data_for_json_value_data_member.number; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonNumber* \
	json_value_get_as_number_mut_ref(JsonValue* const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry->_variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeNumber); \
		return &(variant_entry->_variant_data_for_json_value_data_member.number); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonNumber const* \
	json_value_get_as_number_const_ref(const JsonValue* const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry->_variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeNumber); \
		return &(variant_entry->_variant_data_for_json_value_data_member.number); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonValue \
	new_json_value_string(JsonString* const value) { \
		return (JsonValue){ ._variant_tag_for_json_value_tag_member = JsonValueTypeString, \
			                ._variant_data_for_json_value_data_member = \
			                    (_AnonymousUnionForVariantJsonValueImpl_DONT_USE){ .string = \
			                                                                           value } }; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonString* \
	json_value_get_as_string(JsonValue const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry._variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeString); \
		return variant_entry._variant_data_for_json_value_data_member.string; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonString** \
	json_value_get_as_string_mut_ref(JsonValue* const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry->_variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeString); \
		return &(variant_entry->_variant_data_for_json_value_data_member.string); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonString* const* \
	json_value_get_as_string_const_ref(const JsonValue* const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry->_variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeString); \
		return &(variant_entry->_variant_data_for_json_value_data_member.string); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonValue \
	new_json_value_boolean(JsonBoolean const value) { \
		return (JsonValue){ ._variant_tag_for_json_value_tag_member = JsonValueTypeBoolean, \
			                ._variant_data_for_json_value_data_member = \
			                    (_AnonymousUnionForVariantJsonValueImpl_DONT_USE){ .boolean = \
			                                                                           value } }; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonBoolean \
	json_value_get_as_boolean(JsonValue const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry._variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeBoolean); \
		return variant_entry._variant_data_for_json_value_data_member.boolean; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonBoolean* \
	json_value_get_as_boolean_mut_ref(JsonValue* const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry->_variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeBoolean); \
		return &(variant_entry->_variant_data_for_json_value_data_member.boolean); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonBoolean const* \
	json_value_get_as_boolean_const_ref(const JsonValue* const variant_entry) { \
		VARIANT_JSON_VALUE_STATE_ASSERT(variant_entry->_variant_tag_for_json_value_tag_member, \
		                                JsonValueTypeBoolean); \
		return &(variant_entry->_variant_data_for_json_value_data_member.boolean); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonValue \
	new_json_value_null(void) { \
		return (JsonValue){ ._variant_tag_for_json_value_tag_member = JsonValueTypeNull, \
			                ._variant_data_for_json_value_data_member = \
			                    (_AnonymousUnionForVariantJsonValueImpl_DONT_USE){} }; \
	} \
\
	_Pragma("GCC poison _impl_get_state_string_for_variant_json_value") \
	    __INTERNAL_VARIANT_DECLARATION_END_IMPL_()

#define GENERATE_VARIANT_ALL_JSON_VALUE() \
	GENERATE_VARIANT_ENUM_JSON_VALUE() \
	GENERATE_VARIANT_CORE_JSON_VALUE()

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_CONST_IMPL_2(variant_entry, object)

#define IF_JSON_VALUE_IS_OBJECT_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_CONST_IMPL_2(variant_entry, \
                                                                              var_name) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeObject) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false) \
			for(_variant_impl_unnamed_struct_for_variant_json_value_id_0_name_object_impl_ const \
			        var_name = (variant_entry)._variant_data_for_json_value_data_member.object; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_MUT_MACRO_HELPER_IMPL_(_1, _2, \
                                                                                        NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_MUT_IMPL_2(variant_entry, object)

#define IF_JSON_VALUE_IS_OBJECT_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_OBJECT_MUT_IMPL_2(variant_entry, \
                                                                            var_name) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeObject) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false) \
			for(_variant_impl_unnamed_struct_for_variant_json_value_id_0_name_object_impl_ \
			        var_name = (variant_entry)._variant_data_for_json_value_data_member.object; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false)

#define IF_JSON_VALUE_IS_OBJECT_IGN(variant_entry) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeObject)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_CONST_IMPL_2(variant_entry, array)

#define IF_JSON_VALUE_IS_ARRAY_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_CONST_IMPL_2(variant_entry, \
                                                                             var_name) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeArray) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false) \
			for(_variant_impl_unnamed_struct_for_variant_json_value_id_1_name_array_impl_ const \
			        var_name = (variant_entry)._variant_data_for_json_value_data_member.array; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_MUT_MACRO_HELPER_IMPL_(_1, _2, \
                                                                                       NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_MUT_IMPL_2(variant_entry, array)

#define IF_JSON_VALUE_IS_ARRAY_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_ARRAY_MUT_IMPL_2(variant_entry, \
                                                                           var_name) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeArray) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false) \
			for(_variant_impl_unnamed_struct_for_variant_json_value_id_1_name_array_impl_ \
			        var_name = (variant_entry)._variant_data_for_json_value_data_member.array; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false)

#define IF_JSON_VALUE_IS_ARRAY_IGN(variant_entry) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeArray)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_CONST_IMPL_2(variant_entry, number)

#define IF_JSON_VALUE_IS_NUMBER_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_CONST_IMPL_2(variant_entry, \
                                                                              var_name) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeNumber) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false) \
			for(JsonNumber const var_name = \
			        (variant_entry)._variant_data_for_json_value_data_member.number; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_MUT_MACRO_HELPER_IMPL_(_1, _2, \
                                                                                        NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_MUT_IMPL_2(variant_entry, number)

#define IF_JSON_VALUE_IS_NUMBER_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_NUMBER_MUT_IMPL_2(variant_entry, \
                                                                            var_name) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeNumber) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false) \
			for(JsonNumber var_name = \
			        (variant_entry)._variant_data_for_json_value_data_member.number; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false)

#define IF_JSON_VALUE_IS_NUMBER_IGN(variant_entry) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeNumber)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_CONST_IMPL_2(variant_entry, string)

#define IF_JSON_VALUE_IS_STRING_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_CONST_IMPL_2(variant_entry, \
                                                                              var_name) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeString) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false) \
			for(JsonString* const var_name = \
			        (variant_entry)._variant_data_for_json_value_data_member.string; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_MUT_MACRO_HELPER_IMPL_(_1, _2, \
                                                                                        NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_MUT_IMPL_2(variant_entry, string)

#define IF_JSON_VALUE_IS_STRING_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_STRING_MUT_IMPL_2(variant_entry, \
                                                                            var_name) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeString) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false) \
			for(JsonString* var_name = \
			        (variant_entry)._variant_data_for_json_value_data_member.string; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false)

#define IF_JSON_VALUE_IS_STRING_IGN(variant_entry) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeString)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_CONST_IMPL_2(variant_entry, boolean)

#define IF_JSON_VALUE_IS_BOOLEAN_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_CONST_IMPL_2(variant_entry, \
                                                                               var_name) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeBoolean) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false) \
			for(JsonBoolean const var_name = \
			        (variant_entry)._variant_data_for_json_value_data_member.boolean; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_MUT_IMPL_2(variant_entry, boolean)

#define IF_JSON_VALUE_IS_BOOLEAN_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_VALUE_IS_BOOLEAN_MUT_IMPL_2(variant_entry, \
                                                                             var_name) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeBoolean) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false) \
			for(JsonBoolean var_name = \
			        (variant_entry)._variant_data_for_json_value_data_member.boolean; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl = false)

#define IF_JSON_VALUE_IS_BOOLEAN_IGN(variant_entry) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeBoolean)

#define IF_JSON_VALUE_IS_NULL(variant_entry) \
	if((variant_entry)._variant_tag_for_json_value_tag_member == JsonValueTypeNull)

#define IF_JSON_VALUE_IS_NOT_OBJECT(variant_entry) \
	if((variant_entry)._variant_tag_for_json_value_tag_member != JsonValueTypeObject)

#define IF_JSON_VALUE_IS_NOT_ARRAY(variant_entry) \
	if((variant_entry)._variant_tag_for_json_value_tag_member != JsonValueTypeArray)

#define IF_JSON_VALUE_IS_NOT_NUMBER(variant_entry) \
	if((variant_entry)._variant_tag_for_json_value_tag_member != JsonValueTypeNumber)

#define IF_JSON_VALUE_IS_NOT_STRING(variant_entry) \
	if((variant_entry)._variant_tag_for_json_value_tag_member != JsonValueTypeString)

#define IF_JSON_VALUE_IS_NOT_BOOLEAN(variant_entry) \
	if((variant_entry)._variant_tag_for_json_value_tag_member != JsonValueTypeBoolean)

#define IF_JSON_VALUE_IS_NOT_NULL(variant_entry) \
	if((variant_entry)._variant_tag_for_json_value_tag_member != JsonValueTypeNull)

#define SWITCH_JSON_VALUE(variant_entry) \
	switch((variant_entry)._variant_tag_for_json_value_tag_member)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_CONST_IMPL_2(variant_entry, object)

#define CASE_JSON_VALUE_IS_OBJECT_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_CONST_IMPL_2(variant_entry, \
                                                                                var_name) \
	case JsonValueTypeObject: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false) \
			for(_variant_impl_unnamed_struct_for_variant_json_value_id_0_name_object_impl_ const \
			        var_name = (variant_entry)._variant_data_for_json_value_data_member.object; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_MUT_IMPL_2(variant_entry, object)

#define CASE_JSON_VALUE_IS_OBJECT_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_OBJECT_MUT_IMPL_2(variant_entry, \
                                                                              var_name) \
	case JsonValueTypeObject: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false) \
			for(_variant_impl_unnamed_struct_for_variant_json_value_id_0_name_object_impl_ \
			        var_name = (variant_entry)._variant_data_for_json_value_data_member.object; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false)

#define CASE_JSON_VALUE_IS_OBJECT_IGN() case JsonValueTypeObject:

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_CONST_IMPL_2(variant_entry, array)

#define CASE_JSON_VALUE_IS_ARRAY_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_CONST_IMPL_2(variant_entry, \
                                                                               var_name) \
	case JsonValueTypeArray: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false) \
			for(_variant_impl_unnamed_struct_for_variant_json_value_id_1_name_array_impl_ const \
			        var_name = (variant_entry)._variant_data_for_json_value_data_member.array; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_MUT_IMPL_2(variant_entry, array)

#define CASE_JSON_VALUE_IS_ARRAY_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_ARRAY_MUT_IMPL_2(variant_entry, \
                                                                             var_name) \
	case JsonValueTypeArray: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false) \
			for(_variant_impl_unnamed_struct_for_variant_json_value_id_1_name_array_impl_ \
			        var_name = (variant_entry)._variant_data_for_json_value_data_member.array; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false)

#define CASE_JSON_VALUE_IS_ARRAY_IGN() case JsonValueTypeArray:

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_CONST_IMPL_2(variant_entry, number)

#define CASE_JSON_VALUE_IS_NUMBER_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_CONST_IMPL_2(variant_entry, \
                                                                                var_name) \
	case JsonValueTypeNumber: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false) \
			for(JsonNumber const var_name = \
			        (variant_entry)._variant_data_for_json_value_data_member.number; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_MUT_IMPL_2(variant_entry, number)

#define CASE_JSON_VALUE_IS_NUMBER_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_NUMBER_MUT_IMPL_2(variant_entry, \
                                                                              var_name) \
	case JsonValueTypeNumber: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false) \
			for(JsonNumber var_name = \
			        (variant_entry)._variant_data_for_json_value_data_member.number; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false)

#define CASE_JSON_VALUE_IS_NUMBER_IGN() case JsonValueTypeNumber:

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_CONST_IMPL_2(variant_entry, string)

#define CASE_JSON_VALUE_IS_STRING_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_CONST_IMPL_2(variant_entry, \
                                                                                var_name) \
	case JsonValueTypeString: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false) \
			for(JsonString* const var_name = \
			        (variant_entry)._variant_data_for_json_value_data_member.string; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_MUT_IMPL_2(variant_entry, string)

#define CASE_JSON_VALUE_IS_STRING_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_STRING_MUT_IMPL_2(variant_entry, \
                                                                              var_name) \
	case JsonValueTypeString: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false) \
			for(JsonString* var_name = \
			        (variant_entry)._variant_data_for_json_value_data_member.string; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false)

#define CASE_JSON_VALUE_IS_STRING_IGN() case JsonValueTypeString:

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_CONST_IMPL_2(variant_entry, boolean)

#define CASE_JSON_VALUE_IS_BOOLEAN_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_CONST_IMPL_2(variant_entry, \
                                                                                 var_name) \
	case JsonValueTypeBoolean: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false) \
			for(JsonBoolean const var_name = \
			        (variant_entry)._variant_data_for_json_value_data_member.boolean; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_MUT_IMPL_2(variant_entry, boolean)

#define CASE_JSON_VALUE_IS_BOOLEAN_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_VALUE_IS_BOOLEAN_MUT_IMPL_2(variant_entry, \
                                                                               var_name) \
	case JsonValueTypeBoolean: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false) \
			for(JsonBoolean var_name = \
			        (variant_entry)._variant_data_for_json_value_data_member.boolean; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl = false)

#define CASE_JSON_VALUE_IS_BOOLEAN_IGN() case JsonValueTypeBoolean:

#define CASE_JSON_VALUE_IS_NULL() case JsonValueTypeNull:
// clang-format off
_Pragma ("GCC poison _variant_tag_for_json_value_tag_member _variant_data_for_json_value_data_member _for_macro_trick_for_if_expr_impl_once_variant_json_value_variant_impl _for_macro_trick_for_case_expr_impl_once_variant_json_value_variant_impl _variant_impl_unnamed_struct_for_variant_json_value_id_0_name_object_impl_ _variant_impl_unnamed_struct_for_variant_json_value_id_1_name_array_impl_ _AnonymousUnionForVariantJsonValueImpl_DONT_USE AssertTypeImplForJsonValueImpl_1_DONT_USE_ AssertTypeImplForJsonValueImpl_2_DONT_USE_")
// clang-format on

#define VARIANT_JSON_PARSE_RESULT_STATE_ASSERT(state, expected_state) \
	VARIANT_STATE_ASSERT(state, expected_state, json_parse_result, "JsonParseResult")

#define GENERATE_VARIANT_ENUM_JSON_PARSE_RESULT() \
	/* @enum value */ \
	typedef enum _IMPL_JSON_VARIANTS_C_23_NARROW_ENUM_TO(bool) { \
		JsonParseResultTypeOk = false, \
		JsonParseResultTypeError = true \
	} JsonParseResultType;

#define GENERATE_VARIANT_CORE_JSON_PARSE_RESULT() \
	__INTERNAL_VARIANT_DECLARATION_START_IMPL_() \
	/* raw union for variant */ \
	typedef union { \
		JsonValue ok; \
		JsonError error; \
	} _AnonymousUnionForVariantJsonParseResultImpl_DONT_USE; \
\
	/* tagged union (variant) implementation */ \
	typedef struct { \
		JsonParseResultType _variant_tag_for_json_parse_result_tag_member; \
		_AnonymousUnionForVariantJsonParseResultImpl_DONT_USE \
		    _variant_data_for_json_parse_result_data_member; \
	} JsonParseResult; \
	typedef struct { \
		JsonParseResultType _variant_tag_for_json_parse_result_tag_member; \
		_AnonymousUnionForVariantJsonParseResultImpl_DONT_USE \
		    _variant_data_for_json_parse_result_data_member; \
	} AssertTypeImplForJsonParseResultImpl_1_DONT_USE_; \
	typedef struct { \
		_AnonymousUnionForVariantJsonParseResultImpl_DONT_USE \
		    _variant_data_for_json_parse_result_data_member; \
		JsonParseResultType _variant_tag_for_json_parse_result_tag_member; \
	} AssertTypeImplForJsonParseResultImpl_2_DONT_USE_; \
	static_assert(sizeof(AssertTypeImplForJsonParseResultImpl_1_DONT_USE_) <= \
	                  sizeof(AssertTypeImplForJsonParseResultImpl_2_DONT_USE_), \
	              "Size for variant JsonParseResult not smaller as the inverted order, current " \
	              "order: tag is first"); \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline tstr_static \
	_impl_get_state_string_for_variant_json_parse_result(JsonParseResultType const enum_value) { \
		_Pragma("GCC diagnostic push") \
		    _Pragma("GCC diagnostic ignored \"-Wswitch-bool\"") /* FOR GCC */ \
		    switch(enum_value) { \
		_Pragma("GCC diagnostic pop") case JsonParseResultTypeOk: { \
			return TSTR_STATIC_LIT("ok"); \
		} \
		case JsonParseResultTypeError: { \
			return TSTR_STATIC_LIT("error"); \
		} \
		default: { \
			return TSTR_STATIC_LIT("<unknown>"); \
		} \
		} \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonParseResultType \
	get_current_tag_type_for_json_parse_result(JsonParseResult const variant_entry) { \
		return variant_entry._variant_tag_for_json_parse_result_tag_member; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonParseResult \
	new_json_parse_result_ok(JsonValue const value) { \
		return (JsonParseResult){ \
			._variant_tag_for_json_parse_result_tag_member = JsonParseResultTypeOk, \
			._variant_data_for_json_parse_result_data_member = \
			    (_AnonymousUnionForVariantJsonParseResultImpl_DONT_USE){ .ok = value } \
		}; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonValue \
	json_parse_result_get_as_ok(JsonParseResult const variant_entry) { \
		VARIANT_JSON_PARSE_RESULT_STATE_ASSERT( \
		    variant_entry._variant_tag_for_json_parse_result_tag_member, JsonParseResultTypeOk); \
		return variant_entry._variant_data_for_json_parse_result_data_member.ok; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonValue* \
	json_parse_result_get_as_ok_mut_ref(JsonParseResult* const variant_entry) { \
		VARIANT_JSON_PARSE_RESULT_STATE_ASSERT( \
		    variant_entry->_variant_tag_for_json_parse_result_tag_member, JsonParseResultTypeOk); \
		return &(variant_entry->_variant_data_for_json_parse_result_data_member.ok); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonValue const* \
	json_parse_result_get_as_ok_const_ref(const JsonParseResult* const variant_entry) { \
		VARIANT_JSON_PARSE_RESULT_STATE_ASSERT( \
		    variant_entry->_variant_tag_for_json_parse_result_tag_member, JsonParseResultTypeOk); \
		return &(variant_entry->_variant_data_for_json_parse_result_data_member.ok); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonParseResult \
	new_json_parse_result_error(JsonError const value) { \
		return (JsonParseResult){ \
			._variant_tag_for_json_parse_result_tag_member = JsonParseResultTypeError, \
			._variant_data_for_json_parse_result_data_member = \
			    (_AnonymousUnionForVariantJsonParseResultImpl_DONT_USE){ .error = value } \
		}; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonError \
	json_parse_result_get_as_error(JsonParseResult const variant_entry) { \
		VARIANT_JSON_PARSE_RESULT_STATE_ASSERT( \
		    variant_entry._variant_tag_for_json_parse_result_tag_member, \
		    JsonParseResultTypeError); \
		return variant_entry._variant_data_for_json_parse_result_data_member.error; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonError* \
	json_parse_result_get_as_error_mut_ref(JsonParseResult* const variant_entry) { \
		VARIANT_JSON_PARSE_RESULT_STATE_ASSERT( \
		    variant_entry->_variant_tag_for_json_parse_result_tag_member, \
		    JsonParseResultTypeError); \
		return &(variant_entry->_variant_data_for_json_parse_result_data_member.error); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonError const* \
	json_parse_result_get_as_error_const_ref(const JsonParseResult* const variant_entry) { \
		VARIANT_JSON_PARSE_RESULT_STATE_ASSERT( \
		    variant_entry->_variant_tag_for_json_parse_result_tag_member, \
		    JsonParseResultTypeError); \
		return &(variant_entry->_variant_data_for_json_parse_result_data_member.error); \
	} \
\
	_Pragma("GCC poison _impl_get_state_string_for_variant_json_parse_result") \
	    __INTERNAL_VARIANT_DECLARATION_END_IMPL_()

#define GENERATE_VARIANT_ALL_JSON_PARSE_RESULT() \
	GENERATE_VARIANT_ENUM_JSON_PARSE_RESULT() \
	GENERATE_VARIANT_CORE_JSON_PARSE_RESULT()

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_CONST_IMPL_2(variant_entry, ok)

#define IF_JSON_PARSE_RESULT_IS_OK_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_CONST_IMPL_2(variant_entry, \
                                                                                 var_name) \
	if((variant_entry)._variant_tag_for_json_parse_result_tag_member == JsonParseResultTypeOk) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl = \
		        true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl = false) \
			for(JsonValue const var_name = \
			        (variant_entry)._variant_data_for_json_parse_result_data_member.ok; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl = \
			        false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_MUT_IMPL_2(variant_entry, ok)

#define IF_JSON_PARSE_RESULT_IS_OK_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_OK_MUT_IMPL_2(variant_entry, \
                                                                               var_name) \
	if((variant_entry)._variant_tag_for_json_parse_result_tag_member == JsonParseResultTypeOk) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl = \
		        true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl = false) \
			for(JsonValue var_name = \
			        (variant_entry)._variant_data_for_json_parse_result_data_member.ok; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl = \
			        false)

#define IF_JSON_PARSE_RESULT_IS_OK_IGN(variant_entry) \
	if((variant_entry)._variant_tag_for_json_parse_result_tag_member == JsonParseResultTypeOk)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_CONST_IMPL_2(variant_entry, \
	                                                                            error)

#define IF_JSON_PARSE_RESULT_IS_ERROR_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_CONST_IMPL_2(variant_entry, \
                                                                                    var_name) \
	if((variant_entry)._variant_tag_for_json_parse_result_tag_member == JsonParseResultTypeError) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl = \
		        true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl = false) \
			for(JsonError const var_name = \
			        (variant_entry)._variant_data_for_json_parse_result_data_member.error; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl = \
			        false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_MUT_IMPL_2(variant_entry, error)

#define IF_JSON_PARSE_RESULT_IS_ERROR_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_PARSE_RESULT_IS_ERROR_MUT_IMPL_2(variant_entry, \
                                                                                  var_name) \
	if((variant_entry)._variant_tag_for_json_parse_result_tag_member == JsonParseResultTypeError) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl = \
		        true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl = false) \
			for(JsonError var_name = \
			        (variant_entry)._variant_data_for_json_parse_result_data_member.error; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl = \
			        false)

#define IF_JSON_PARSE_RESULT_IS_ERROR_IGN(variant_entry) \
	if((variant_entry)._variant_tag_for_json_parse_result_tag_member == JsonParseResultTypeError)

#define IF_JSON_PARSE_RESULT_IS_NOT_OK(variant_entry) \
	if((variant_entry)._variant_tag_for_json_parse_result_tag_member != JsonParseResultTypeOk)

#define IF_JSON_PARSE_RESULT_IS_NOT_ERROR(variant_entry) \
	if((variant_entry)._variant_tag_for_json_parse_result_tag_member != JsonParseResultTypeError)

#define SWITCH_JSON_PARSE_RESULT(variant_entry) \
	_Pragma("GCC diagnostic push") \
	    _Pragma("GCC diagnostic ignored \"-Wswitch-bool\"") /* FOR GCC */ switch( \
	        (variant_entry)._variant_tag_for_json_parse_result_tag_member) \
	        _Pragma("GCC diagnostic pop")

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_CONST_IMPL_2(variant_entry, ok)

#define CASE_JSON_PARSE_RESULT_IS_OK_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_CONST_IMPL_2(variant_entry, \
                                                                                   var_name) \
	case JsonParseResultTypeOk: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl = \
		        true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl = \
		        false) \
			for(JsonValue const var_name = \
			        (variant_entry)._variant_data_for_json_parse_result_data_member.ok; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl = \
			        false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_MUT_IMPL_2(variant_entry, ok)

#define CASE_JSON_PARSE_RESULT_IS_OK_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_OK_MUT_IMPL_2(variant_entry, \
                                                                                 var_name) \
	case JsonParseResultTypeOk: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl = \
		        true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl = \
		        false) \
			for(JsonValue var_name = \
			        (variant_entry)._variant_data_for_json_parse_result_data_member.ok; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl = \
			        false)

#define CASE_JSON_PARSE_RESULT_IS_OK_IGN() case JsonParseResultTypeOk:

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_CONST_IMPL_1( \
    variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_CONST_IMPL_2(variant_entry, \
	                                                                              error)

#define CASE_JSON_PARSE_RESULT_IS_ERROR_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_CONST_IMPL_1)( \
	    __VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_CONST_IMPL_2( \
    variant_entry, var_name) \
	case JsonParseResultTypeError: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl = \
		        true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl = \
		        false) \
			for(JsonError const var_name = \
			        (variant_entry)._variant_data_for_json_parse_result_data_member.error; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl = \
			        false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_MUT_IMPL_2(variant_entry, \
	                                                                            error)

#define CASE_JSON_PARSE_RESULT_IS_ERROR_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_PARSE_RESULT_IS_ERROR_MUT_IMPL_2(variant_entry, \
                                                                                    var_name) \
	case JsonParseResultTypeError: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl = \
		        true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl = \
		        false) \
			for(JsonError var_name = \
			        (variant_entry)._variant_data_for_json_parse_result_data_member.error; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl = \
			        false)

#define CASE_JSON_PARSE_RESULT_IS_ERROR_IGN() case JsonParseResultTypeError:

    // clang-format off
_Pragma ("GCC poison _variant_tag_for_json_parse_result_tag_member _variant_data_for_json_parse_result_data_member _for_macro_trick_for_if_expr_impl_once_variant_json_parse_result_variant_impl _for_macro_trick_for_case_expr_impl_once_variant_json_parse_result_variant_impl _AnonymousUnionForVariantJsonParseResultImpl_DONT_USE AssertTypeImplForJsonParseResultImpl_1_DONT_USE_ AssertTypeImplForJsonParseResultImpl_2_DONT_USE_")
// clang-format on

#define VARIANT_JSON_SOURCE_STATE_ASSERT(state, expected_state) \
	VARIANT_STATE_ASSERT(state, expected_state, json_source, "JsonSource")

#define GENERATE_VARIANT_ENUM_JSON_SOURCE() \
	/* @enum value */ \
	typedef enum _IMPL_JSON_VARIANTS_C_23_NARROW_ENUM_TO(bool) { \
		JsonSourceTypeFile = false, \
		JsonSourceTypeString = true \
	} JsonSourceType;

#define GENERATE_VARIANT_CORE_JSON_SOURCE() \
	__INTERNAL_VARIANT_DECLARATION_START_IMPL_() \
	/* raw union for variant */ \
	typedef union { \
		JsonFileSource file; \
		JsonStringSource string; \
	} _AnonymousUnionForVariantJsonSourceImpl_DONT_USE; \
\
	/* tagged union (variant) implementation */ \
	typedef struct { \
		JsonSourceType _variant_tag_for_json_source_tag_member; \
		_AnonymousUnionForVariantJsonSourceImpl_DONT_USE \
		    _variant_data_for_json_source_data_member; \
	} JsonSource; \
	typedef struct { \
		JsonSourceType _variant_tag_for_json_source_tag_member; \
		_AnonymousUnionForVariantJsonSourceImpl_DONT_USE \
		    _variant_data_for_json_source_data_member; \
	} AssertTypeImplForJsonSourceImpl_1_DONT_USE_; \
	typedef struct { \
		_AnonymousUnionForVariantJsonSourceImpl_DONT_USE \
		    _variant_data_for_json_source_data_member; \
		JsonSourceType _variant_tag_for_json_source_tag_member; \
	} AssertTypeImplForJsonSourceImpl_2_DONT_USE_; \
	static_assert(sizeof(AssertTypeImplForJsonSourceImpl_1_DONT_USE_) <= \
	                  sizeof(AssertTypeImplForJsonSourceImpl_2_DONT_USE_), \
	              "Size for variant JsonSource not smaller as the inverted order, current order: " \
	              "tag is first"); \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline tstr_static \
	_impl_get_state_string_for_variant_json_source(JsonSourceType const enum_value) { \
		_Pragma("GCC diagnostic push") \
		    _Pragma("GCC diagnostic ignored \"-Wswitch-bool\"") /* FOR GCC */ \
		    switch(enum_value) { \
		_Pragma("GCC diagnostic pop") case JsonSourceTypeFile: { return TSTR_STATIC_LIT("file"); } \
		case JsonSourceTypeString: { \
			return TSTR_STATIC_LIT("string"); \
		} \
		default: { \
			return TSTR_STATIC_LIT("<unknown>"); \
		} \
		} \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonSourceType \
	get_current_tag_type_for_json_source(JsonSource const variant_entry) { \
		return variant_entry._variant_tag_for_json_source_tag_member; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonSource \
	new_json_source_file(JsonFileSource const value) { \
		return (JsonSource){ ._variant_tag_for_json_source_tag_member = JsonSourceTypeFile, \
			                 ._variant_data_for_json_source_data_member = \
			                     (_AnonymousUnionForVariantJsonSourceImpl_DONT_USE){ \
			                         .file = value } }; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonFileSource \
	json_source_get_as_file(JsonSource const variant_entry) { \
		VARIANT_JSON_SOURCE_STATE_ASSERT(variant_entry._variant_tag_for_json_source_tag_member, \
		                                 JsonSourceTypeFile); \
		return variant_entry._variant_data_for_json_source_data_member.file; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonFileSource* \
	json_source_get_as_file_mut_ref(JsonSource* const variant_entry) { \
		VARIANT_JSON_SOURCE_STATE_ASSERT(variant_entry->_variant_tag_for_json_source_tag_member, \
		                                 JsonSourceTypeFile); \
		return &(variant_entry->_variant_data_for_json_source_data_member.file); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonFileSource const* \
	json_source_get_as_file_const_ref(const JsonSource* const variant_entry) { \
		VARIANT_JSON_SOURCE_STATE_ASSERT(variant_entry->_variant_tag_for_json_source_tag_member, \
		                                 JsonSourceTypeFile); \
		return &(variant_entry->_variant_data_for_json_source_data_member.file); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonSource \
	new_json_source_string(JsonStringSource const value) { \
		return (JsonSource){ ._variant_tag_for_json_source_tag_member = JsonSourceTypeString, \
			                 ._variant_data_for_json_source_data_member = \
			                     (_AnonymousUnionForVariantJsonSourceImpl_DONT_USE){ \
			                         .string = value } }; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonStringSource \
	json_source_get_as_string(JsonSource const variant_entry) { \
		VARIANT_JSON_SOURCE_STATE_ASSERT(variant_entry._variant_tag_for_json_source_tag_member, \
		                                 JsonSourceTypeString); \
		return variant_entry._variant_data_for_json_source_data_member.string; \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonStringSource* \
	json_source_get_as_string_mut_ref(JsonSource* const variant_entry) { \
		VARIANT_JSON_SOURCE_STATE_ASSERT(variant_entry->_variant_tag_for_json_source_tag_member, \
		                                 JsonSourceTypeString); \
		return &(variant_entry->_variant_data_for_json_source_data_member.string); \
	} \
\
	JSON_VARIANTS_NODISCARD JSON_VARIANTS_MAYBE_UNUSED static inline JsonStringSource const* \
	json_source_get_as_string_const_ref(const JsonSource* const variant_entry) { \
		VARIANT_JSON_SOURCE_STATE_ASSERT(variant_entry->_variant_tag_for_json_source_tag_member, \
		                                 JsonSourceTypeString); \
		return &(variant_entry->_variant_data_for_json_source_data_member.string); \
	} \
\
	_Pragma("GCC poison _impl_get_state_string_for_variant_json_source") \
	    __INTERNAL_VARIANT_DECLARATION_END_IMPL_()

#define GENERATE_VARIANT_ALL_JSON_SOURCE() \
	GENERATE_VARIANT_ENUM_JSON_SOURCE() \
	GENERATE_VARIANT_CORE_JSON_SOURCE()

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_CONST_IMPL_2(variant_entry, file)

#define IF_JSON_SOURCE_IS_FILE_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_CONST_IMPL_2(variant_entry, \
                                                                             var_name) \
	if((variant_entry)._variant_tag_for_json_source_tag_member == JsonSourceTypeFile) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl = false) \
			for(JsonFileSource const var_name = \
			        (variant_entry)._variant_data_for_json_source_data_member.file; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_MUT_MACRO_HELPER_IMPL_(_1, _2, \
                                                                                       NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_MUT_IMPL_2(variant_entry, file)

#define IF_JSON_SOURCE_IS_FILE_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_FILE_MUT_IMPL_2(variant_entry, \
                                                                           var_name) \
	if((variant_entry)._variant_tag_for_json_source_tag_member == JsonSourceTypeFile) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl = false) \
			for(JsonFileSource var_name = \
			        (variant_entry)._variant_data_for_json_source_data_member.file; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl = false)

#define IF_JSON_SOURCE_IS_FILE_IGN(variant_entry) \
	if((variant_entry)._variant_tag_for_json_source_tag_member == JsonSourceTypeFile)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_CONST_IMPL_2(variant_entry, string)

#define IF_JSON_SOURCE_IS_STRING_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_CONST_IMPL_2(variant_entry, \
                                                                               var_name) \
	if((variant_entry)._variant_tag_for_json_source_tag_member == JsonSourceTypeString) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl = false) \
			for(JsonStringSource const var_name = \
			        (variant_entry)._variant_data_for_json_source_data_member.string; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_MUT_IMPL_2(variant_entry, string)

#define IF_JSON_SOURCE_IS_STRING_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_IF_JSON_SOURCE_IS_STRING_MUT_IMPL_2(variant_entry, \
                                                                             var_name) \
	if((variant_entry)._variant_tag_for_json_source_tag_member == JsonSourceTypeString) \
		for(bool _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl = true; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl; \
		    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl = false) \
			for(JsonStringSource var_name = \
			        (variant_entry)._variant_data_for_json_source_data_member.string; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl; \
			    _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl = false)

#define IF_JSON_SOURCE_IS_STRING_IGN(variant_entry) \
	if((variant_entry)._variant_tag_for_json_source_tag_member == JsonSourceTypeString)

#define IF_JSON_SOURCE_IS_NOT_FILE(variant_entry) \
	if((variant_entry)._variant_tag_for_json_source_tag_member != JsonSourceTypeFile)

#define IF_JSON_SOURCE_IS_NOT_STRING(variant_entry) \
	if((variant_entry)._variant_tag_for_json_source_tag_member != JsonSourceTypeString)

#define SWITCH_JSON_SOURCE(variant_entry) \
	_Pragma("GCC diagnostic push") \
	    _Pragma("GCC diagnostic ignored \"-Wswitch-bool\"") /* FOR GCC */ switch( \
	        (variant_entry)._variant_tag_for_json_source_tag_member) _Pragma("GCC diagnostic pop")

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_CONST_IMPL_2(variant_entry, file)

#define CASE_JSON_SOURCE_IS_FILE_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_CONST_IMPL_2(variant_entry, \
                                                                               var_name) \
	case JsonSourceTypeFile: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl = false) \
			for(JsonFileSource const var_name = \
			        (variant_entry)._variant_data_for_json_source_data_member.file; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_MUT_IMPL_2(variant_entry, file)

#define CASE_JSON_SOURCE_IS_FILE_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_FILE_MUT_IMPL_2(variant_entry, \
                                                                             var_name) \
	case JsonSourceTypeFile: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl = false) \
			for(JsonFileSource var_name = \
			        (variant_entry)._variant_data_for_json_source_data_member.file; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl = false)

#define CASE_JSON_SOURCE_IS_FILE_IGN() case JsonSourceTypeFile:

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_CONST_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_CONST_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_CONST_IMPL_2(variant_entry, string)

#define CASE_JSON_SOURCE_IS_STRING_CONST(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_CONST_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_CONST_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_CONST_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_CONST_IMPL_2(variant_entry, \
                                                                                 var_name) \
	case JsonSourceTypeString: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl = false) \
			for(JsonStringSource const var_name = \
			        (variant_entry)._variant_data_for_json_source_data_member.string; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl = false)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_MUT_MACRO_HELPER_IMPL_( \
    _1, _2, NAME, ...) \
	NAME

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_MUT_IMPL_1(variant_entry) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_MUT_IMPL_2(variant_entry, string)

#define CASE_JSON_SOURCE_IS_STRING_MUT(...) \
	__INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_MUT_MACRO_HELPER_IMPL_( \
	    __VA_ARGS__, __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_MUT_IMPL_2, \
	    __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_MUT_IMPL_1)(__VA_ARGS__)

#define __INTERNAL_HELPER_MACRO_DONT_USE_CASE_JSON_SOURCE_IS_STRING_MUT_IMPL_2(variant_entry, \
                                                                               var_name) \
	case JsonSourceTypeString: \
		for(bool _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl = true; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl; \
		    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl = false) \
			for(JsonStringSource var_name = \
			        (variant_entry)._variant_data_for_json_source_data_member.string; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl; \
			    _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl = false)

#define CASE_JSON_SOURCE_IS_STRING_IGN() case JsonSourceTypeString:

    // clang-format off
_Pragma ("GCC poison _variant_tag_for_json_source_tag_member _variant_data_for_json_source_data_member _for_macro_trick_for_if_expr_impl_once_variant_json_source_variant_impl _for_macro_trick_for_case_expr_impl_once_variant_json_source_variant_impl _AnonymousUnionForVariantJsonSourceImpl_DONT_USE AssertTypeImplForJsonSourceImpl_1_DONT_USE_ AssertTypeImplForJsonSourceImpl_2_DONT_USE_")
    // clang-format on
